global:
  enable: true
  tlsDisable: false

ui:
  enabled: true
  serviceType: LoadBalancer #ClusterIP

server:
  standalone:
    config: "# Using custom config"
  
  extraArgs: "-config=/vault/userconfig/server.hcl"
  
  extraEnvironmentVars:
    VAULT_CACERT: /vault/tls/ca.pem
  
  volumes:
  - name: userconfig
    configMap:
      name: userconfig
  - name: usersecret
    secret:
      defaultMode: 420
      secretName: usersecret
  
  volumeMounts:
  - name: userconfig
    mountPath: /vault/userconfig
    readOnly: true
  - name: usersecret
    mountPath: /vault/tls
    readOnly: true
  
  dataStorage:
    enabled: true
    size: 5Gi
  
  auditStorage:
    enabled: false
    size: 5Gi
  
  resources:
    requests:
      memory: 125Mi
      cpu: 125m
    limits:
      memory: 250Mi
      cpu: 250m
